### ISSUE TITLE
Crash when running tests

### ISSUE THREAD

**Issue by bolandrm** [sorich87/bootstrap-tour#440]
I'm getting the following error when I try to run the tests.  I'm using node 0.12.4.  Anyone else run into this?

```
bootstrap-tour (master) →  gulp test
[12:08:13] Warning: gulp version mismatch:
[12:08:13] Global gulp is 3.9.0
[12:08:13] Local gulp is 3.8.11
[12:08:16] Using gulpfile ~/www/gems/bootstrap-tour/gulpfile.js
[12:08:16] Starting 'coffee'...
[12:08:17] Finished 'coffee' after 1.12 s
[12:08:17] Starting 'test-coffee'...
[12:08:18] Finished 'test-coffee' after 573 ms
[12:08:18] Starting 'test-go'...
INFO [karma]: Karma v0.12.36 server started at http://localhost:9876/
INFO [launcher]: Starting browser Firefox
WARN [web-server]: 404: /favicon.ico
INFO [Firefox 38.0.0 (Mac OS X 10.10.0)]: Connected on socket PkXyAksf8IULYYtVk-3s with id 80641893
Firefox 38.0.0 (Mac OS X 10.10.0) ERROR
  TypeError: can't convert undefined to object
  at /Users/bolandrm/www/gems/bootstrap-tour/bower_components/jquery/dist/jquery.js:4268
Firefox 38.0.0 (Mac OS X 10.10.0): Executed 65 of 79 ERROR (0.603 secs / 0.476 secs)
[12:08:20] 'test-go' errored after 2.43 s
[12:08:20] Error: 1
  at formatError (/Users/bolandrm/npm-global/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/Users/bolandrm/npm-global/lib/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.emit (events.js:107:17)
  at Gulp.Orchestrator._emitTaskDone (/Users/bolandrm/www/gems/bootstrap-tour/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /Users/bolandrm/www/gems/bootstrap-tour/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/Users/bolandrm/www/gems/bootstrap-tour/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/bolandrm/www/gems/bootstrap-tour/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at removeAllListeners (/Users/bolandrm/www/gems/bootstrap-tour/node_modules/karma/lib/server.js:218:7)
  at Server.<anonymous> (/Users/bolandrm/www/gems/bootstrap-tour/node_modules/karma/lib/server.js:229:9)
  at Server.g (events.js:199:16)
  at Server.emit (events.js:129:20)
  at net.js:1419:10
  at process._tickCallback (node.js:355:11)
```

**Comment by sorich87** [comment]
It happens intermittently on Travis too https://travis-ci.org/sorich87/bootstrap-tour/builds.

**Comment by ousram** [comment]
This won't no longer happen since we replace Firefox by PhantomJS to run the tests.
