### ISSUE TITLE
Issue: Bootstrap Tour Error with 'tip' property

### ISSUE THREAD

**Issue by vijayan108** [sorich87/bootstrap-tour#777]
### Description:  
I'm facing a challenge when trying to implement a tour on my website using the Bootstrap Tour library. While the tour correctly identifies the elements, it fails to display the content and title as expected.

### Code Sample:

```javascript
function startTour() {
    var labtour = new Tour({
        name: "labtour",
        storage: window.localStorage,
        debug: true,
    });

    labtour.addSteps([{
        element: "#lab-tour",
        title: "Lab",
        content: "This is the lab. You can create and manage your experiments here.",
        placement: "bottom",
        backdrop: true,
        animation: true,
    }, {
        element: "#lab-tour-1",
        title: "Lab",
        content: "This is the lab. You can create and manage your experiments here.",
        placement: "right",
        backdrop: true,
        animation: true,
    }]);
    labtour.init();
    labtour.start();
}
```

### Error Stack Trace:

```
bootstrap-tour.js:597  Uncaught TypeError: Cannot read properties of undefined (reading 'tip')
    at Tour._showPopover (bootstrap-tour.js:597:113)
    at Tour._showPopoverAndOverlay (bootstrap-tour.js:552:18)
    at Tour._showPopoverAndOverlay (bootstrap-tour.js:22:61)
    at HTMLBodyElement.<anonymous> (bootstrap-tour.js:717:31)
    at r.complete (jquery.min.js?_=v0.4-beta-555-gb4f99e00:2:62910)
    at c (jquery.min.js?_=v0.4-beta-555-gb4f99e00:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js?_=v0.4-beta-555-gb4f99e00:2:29072)
    at u (jquery.min.js?_=v0.4-beta-555-gb4f99e00:2:59642)
    at S.fx.tick (jquery.min.js?_=v0.4-beta-555-gb4f99e00:2:64608)
    at ot (jquery.min.js?_=v0.4-beta-555-gb4f99e00:2:58967)
    


```

### Additional Context:
All dependencies have been verified to load correctly and in the appropriate order. I'm seeking insights or suggestions to resolve this issue.

**Comment by zthomas1** [comment]
I am having the exact same issue when running with bootstrap 5.3

**Comment by whsimonds** [comment]
Getting the same issue

**Comment by zthomas1** [comment]
for what its worth, we decided to switch our application to drivers js for this functionality.

**Comment by vijayan108** [comment]
but someone recommend me any like bootstrap tour but it should has path like where i can able show the tour for different path also because tour application are showing in single page
